services:
  mysql:
    image: mysql:8.0
    container_name: kh3t-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kh3t_shop
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  

  backend:
    build: ./kh3tshop-be
    container_name: kh3t-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mysql:3306/kh3t_shop?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./kh3tshop-fe
    container_name: kh3t-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend


volumes:
  mysql_data:
  # jenkins_data:  # disabled
