server:
  port: 8080

spring:
  application:
    name: kh3t-gateway
  cloud:
    gateway:
      routes:
        # ===== IDENTITY SERVICE =====
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/auth/**, /api/accounts/**, /api/customers/**, /api/addresses/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # ===== CATALOG SERVICE =====
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/products/**, /api/categories/**, /api/sizes/**, /api/size-details/**, /api/sizedetails/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # ===== ORDER SERVICE =====
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**, /api/order-details/**, /api/invoices/**, /api/carts/**, /api/cart-details/**, /api/wishlists/**, /api/wishlist-details/**, /api/sepay/**, /api/customertradings/**, /api/customer-trading/**, /api/v1/payment/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

security:
  jwt:
    secret: changeme
