server:
  port: 8080

spring:
  application:
    name: kh3t-gateway
  cloud:
    gateway:
      routes:
        # ===== IDENTITY SERVICE =====
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/auth/**, /api/accounts/**, /api/customers/**, /api/addresses/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # ===== CATALOG SERVICE =====
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/products/**, /api/categories/**, /api/sizes/**, /api/size-details/**, /api/sizedetails/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # ===== ORDER SERVICE =====
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**, /api/order-details/**, /api/invoices/**, /api/carts/**, /api/cart-details/**, /api/wishlists/**, /api/wishlist-details/**, /api/sepay/**, /api/customertradings/**, /api/customer-trading/**, /api/v1/payment/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # ===== AI SERVICE =====
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/chat/**, /api/admin-chat/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173"
              - "https://kh3tshop-fe.vercel.app"
              - "https://kh3tshop-k08vijg7u-thanh123aaas-projects.vercel.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

security:
  jwt:
    secret: c8e09fddda9e192d16c485affabc61c9f4bca77a60c19d448f3a6e8475b9f0a4e0d1f69bca8d21f1123b8f0f8a0b8d12
